config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :fretes do
  	post :fechar
  	post :concluir
  	post :not_show
    post :not_show_ajudante
  	post :solicitar_ajudante
  	post :avaliar_ajudante
  	post :ajudante_avaliar_motorista
  end
  resource :drivers
  resource :people
  resource :helpers
	get '/dashboard', to: 'dashboard#show', as: 'dashboard'
	get '/dashboard/:id/results', to: 'dashboard#results', as: 'dashboard/results'
	# get '/dashboard/:id/helper_results', to: 'dashboard#helper_results', as: 'dashboard/helper_results'
	get '/result/:id', to: 'result#result', as: 'result'
	# get '/fretes/:id/status', to: 'fretes#status'

	root to: 'dashboard#show', as: 'home'

	get '/help', to: 'help#show', as: 'help'

	# unauthenticated do
 #   root :to => 'home#show', as: 'home'
	# end

	# authenticated do
	#   root :to => 'dashboard#show', as: 'dashome'
	# end
end

app/models/frete.rb
class Frete < ApplicationRecord
	has_many :results, autosave: true
	has_many :ratings, autosave: true
	accepts_nested_attributes_for :results

	validates :cep_origem, presence: true

	def build_link
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where.not(driver_id: nil).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_motorista(driver_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where(driver_id: driver_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		self.results.where(solicitado_motorista_id: driver_id).each do |result|
			link += "&markers=color:blue|label:A|#{result.latitude_ajudante},#{result.longitude_ajudante}"
			# link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_ajudante(helper_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"

		result_ajudante = self.results.where(helper_id: helper_id).first
		link += "&markers=color:blue|label:A|#{result_ajudante.latitude_ajudante},#{result_ajudante.longitude_ajudante}"

		self.results.where(driver_id: result_ajudante.solicitado_motorista_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end
end

app/controllers/fretes_controller.rb
class FretesController < ApplicationController
	def new
		@frete = Frete.new()
		@estados = State.estados
	end

	def edit
		@frete = Frete.find(params.permit![:id])
		@estados = State.estados
	end

	def update
		@frete = Frete.find(params.permit![:frete][:id])
		@frete.update_attributes(params.permit![:frete])
		Calcular.new.perform(@frete.id)
		redirect_to dashboard_path(id: @frete.id), notice: "Frete atualizado com sucesso!"
	end


	def create
		@frete = Frete.new(params.permit![:frete])
		@frete.user_id = current_user.id
		if @frete.save
			Calcular.new.perform(@frete.id)
			redirect_to dashboard_path(@frete.id)
		else
			render 'new'
		end
	end

	def fechar
		@frete = Frete.find(params.permit![:id])
		@frete.update_attributes(fechado: true)
		redirect_to dashboard_path(@frete.id)
	end

	def concluir
		nota = 0
    if params.permit![:star_1] == true
      nota = 1
    elsif params.permit![:star_2] == true
      nota = 2
    elsif params.permit![:star_3] == true
      nota = 3
    elsif params.permit![:star_4] == true
      nota = 4
    elsif params.permit![:star_5] == true
      nota = 5
    end

		@frete = Frete.find(params.permit![:frete_id])
		@frete.update_attributes(concluido: true)

		Rating.create(nota: nota, frete_id: @frete.id, driver_id: params.permit![:driver_id])
		# redirect_to dashboard_path(@frete.id)
		true
	end

	def not_show
		@frete = Frete.find(params.permit![:id])
		@frete.update_attributes(oculto: true)
		redirect_to dashboard_path(@frete.id)
	end

	def not_show_ajudante
		@frete = Frete.find(params.permit![:id])
		@frete.update_attributes(oculto_ajudante: true)
		redirect_to dashboard_path(@frete.id)
	end

	def solicitar_ajudante
		@frete = Frete.find(params.permit![:id])
		CalcularAjudante.new.perform(@frete.id, current_user.motorista_id)
		redirect_to dashboard_path(@frete.id)
	end

	def avaliar_ajudante
		nota = 0
    if params.permit![:star_1] == true
      nota = 1
    elsif params.permit![:star_2] == true
      nota = 2
    elsif params.permit![:star_3] == true
      nota = 3
    elsif params.permit![:star_4] == true
      nota = 4
    elsif params.permit![:star_5] == true
      nota = 5
    end

		@frete = Frete.find(params.permit![:frete_id])
		rating = Rating.new(nota: nota, frete_id: @frete.id, helper_id: params.permit![:helper_id])
		rating.save(validate: false)
		# redirect_to dashboard_results_path(@frete.id)
		true
	end

	def ajudante_avaliar_motorista
		nota = 0
    if params.permit![:star_1] == true
      nota = 1
    elsif params.permit![:star_2] == true
      nota = 2
    elsif params.permit![:star_3] == true
      nota = 3
    elsif params.permit![:star_4] == true
      nota = 4
    elsif params.permit![:star_5] == true
      nota = 5
    end

		@frete = Frete.find(params.permit![:frete_id])
		frete_rating = Rating.where(frete_id: @frete.id, nota_pelo_ajudante: false).first
		rating = Rating.new(nota: nota, frete_id: @frete.id, driver_id: frete_rating.driver_id, nota_pelo_ajudante: true)
		rating.save(validate: false)
		# redirect_to dashboard_path
		true
	end
end

app/helpers/fretes_helper.rb
module FretesHelper
end

app/views/fretes/_form.haml
= javascript_pack_tag "busca_cep.js"
= javascript_pack_tag "set_mask.js"
.card
	= bootstrap_form_with(model: @frete, url: fretes_path, class: "needs-validation", html: { novalidate: true }) do |f|
		=f.hidden_field :id
		-if @frete.new_record?
			%h5 Novo Frete
		-else
			%h5 Editar Frete
		.row
			.col-md-2
				=f.text_field :cep_origem, class: "c_cep", id: 'cep_origem', required: true
			.col-md-8
				=f.text_field :rua_origem, id: 'rua_origem', required: true
			.col-md-2
				=f.text_field :numero_origem, required: true
			.col-md-4
				=f.text_field :complemento_origem
			.col-md-3
				=f.text_field :bairro_origem, id: 'bairro_origem'
			.col-md-3
				=f.text_field :cidade_origem, id: 'cidade_origem', required: true
			.col-md-2
				=f.select :uf_origem, options_for_select(State.estados, f.object.uf_origem),{}, id: "uf_origem", required: true
		.row
			.col-md-2
				=f.text_field :cep_destino, class: "c_cep", id: 'cep_destino', required: true
			.col-md-8
				=f.text_field :rua_destino, id: 'rua_destino', required: true
			.col-md-2
				=f.text_field :numero_destino, required: true
			.col-md-4
				=f.text_field :complemento_destino
			.col-md-3
				=f.text_field :bairro_destino, id: 'bairro_destino'
			.col-md-3
				=f.text_field :cidade_destino, id: 'cidade_destino', required: true
			.col-md-2
				=f.select :uf_destino, options_for_select(State.estados, f.object.uf_destino),{}, id: "uf_destino", required: true
		.row
			.col-md-4
				=f.select :tamanho, options_for_select([["Poucos itens",1], ["1 Cômodo",2],["2 Cômodos",3],["3 ou mais Cômodos", 4]], f.object.tamanho),{}, required: true
		.row
			.col
				-if @frete.new_record?
					= f.submit "Gravar", id: "btn", class: "btn btn-primary float-right"
				-else
					= f.submit "Salvar Alterações", id: "btn", class: "btn btn-primary float-right"
:javascript
	(function() {
	'use strict';
		window.addEventListener('load', function() {
			// Fetch all the forms we want to apply custom Bootstrap validation styles to
			var forms = document.getElementsByClassName('needs-validation');
			// Loop over them and prevent submission
			var validation = Array.prototype.filter.call(forms, function(form) {
			form.addEventListener('submit', function(event) {
				if (form.checkValidity() === false) {
					event.preventDefault();
					event.stopPropagation();
				}
					form.classList.add('was-validated');
				}, false);
			});
		}, false);
	})();

app/views/fretes/edit.haml
=render 'form'

app/views/fretes/new.haml
=render 'form'