config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :fretes do
  	post :fechar
  	post :concluir
  	post :not_show
    post :not_show_ajudante
  	post :solicitar_ajudante
  	post :avaliar_ajudante
  	post :ajudante_avaliar_motorista
  end
  resource :drivers
  resource :people
  resource :helpers
	get '/dashboard', to: 'dashboard#show', as: 'dashboard'
	get '/dashboard/:id/results', to: 'dashboard#results', as: 'dashboard/results'
	# get '/dashboard/:id/helper_results', to: 'dashboard#helper_results', as: 'dashboard/helper_results'
	get '/result/:id', to: 'result#result', as: 'result'
	# get '/fretes/:id/status', to: 'fretes#status'

	root to: 'dashboard#show', as: 'home'

	get '/help', to: 'help#show', as: 'help'

	# unauthenticated do
 #   root :to => 'home#show', as: 'home'
	# end

	# authenticated do
	#   root :to => 'dashboard#show', as: 'dashome'
	# end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
	has_many :results
	has_many :ratings

	def nota
		average = self.ratings.average(:nota)
		html = ''
		5.times do |nota|
			if average.to_f == 0.0
				html += '<i class="far fa-star"></i>'
			else
				if nota < average.to_i
					html += '<i class="fas fa-star"></i>'
				elsif nota == average.to_i  && (average.to_f - average.to_i).round == 1
					html += '<i class="fas fa-star-half"></i>'
				else
					html += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
				end
			end
		end
		html += "&nbsp;&nbsp;<span>#{'%.1f' % average.to_f}</span>"
		html
	end

	def veiculo_texto
		case self.tipo_veiculo
		when 1
			"Pickup"
		when 2
			"Van/Vuc"
		when 3
			"Caminhão"
		end
	end

end

app/models/frete.rb
class Frete < ApplicationRecord
	has_many :results, autosave: true
	has_many :ratings, autosave: true
	accepts_nested_attributes_for :results

	validates :cep_origem, presence: true

	def build_link
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where.not(driver_id: nil).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_motorista(driver_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where(driver_id: driver_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		self.results.where(solicitado_motorista_id: driver_id).each do |result|
			link += "&markers=color:blue|label:A|#{result.latitude_ajudante},#{result.longitude_ajudante}"
			# link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_ajudante(helper_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"

		result_ajudante = self.results.where(helper_id: helper_id).first
		link += "&markers=color:blue|label:A|#{result_ajudante.latitude_ajudante},#{result_ajudante.longitude_ajudante}"

		self.results.where(driver_id: result_ajudante.solicitado_motorista_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end
end

app/models/helper.rb
class Helper < ApplicationRecord
	has_many :ratings
	has_many :results

	def nota
		average = self.ratings.average(:nota)
		html = ''
		5.times do |nota|
			if average.to_f == 0.0
				html += '<i class="far fa-star"></i>'
			else
				if nota < average.to_i
					html += '<i class="fas fa-star"></i>'
				elsif nota == average.to_i  && (average.to_f - average.to_i).round == 1
					html += '<i class="fas fa-star-half"></i>'
				else
					html += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
				end
			end
		end
		html += "&nbsp;&nbsp;<span>#{'%.1f' % average.to_f}</span>"
		html
	end
end

app/models/helper_rating.rb
class HelperRating < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :driver
	belongs_to :frete
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :frete
	belongs_to :driver
	belongs_to :helper
end

app/models/state.rb
class State < ApplicationRecord

	def self.estados
		self.pluck(:sigla)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :is_complete, :user_name

  def user_name
  	if self.is_complete
  		if self.usuario
  			Person.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		elsif self.motorista
  			Driver.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		else
  			Helper.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		end
  	else
  		'Cadastre-se!'
  	end
  end

  def is_complete
  	self.usuario || self.ajudante || self.motorista
  end

  def usuario_id
  	Person.find_by(user_id: self.id).id
  end

  def motorista_id
    Driver.find_by(user_id: self.id).id
  end

  def ajudante_id
    Helper.find_by(user_id: self.id).id
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def show
		if current_user.usuario
			@fretes = Frete.where(user_id: current_user.id).order(id: :desc)
		elsif current_user.motorista
			@fretes = Frete.joins(:results).where(oculto: false, results: {driver_id: current_user.motorista_id}).order(id: :desc)
		elsif current_user.ajudante
			@fretes = Frete.joins(:results).where(oculto_ajudante: false, results: {helper_id: current_user.ajudante_id}).order(id: :desc).uniq
		end
	end

	def results
		if current_user.usuario
			@results = Frete.find(params.permit![:id]).results.where.not(driver_id: nil)
		elsif current_user.motorista
			@results = Frete.find(params.permit![:id]).results.where(solicitado_motorista_id: current_user.motorista_id)
		end
	end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fretes_helper.rb
module FretesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/dashboard/results.haml
= javascript_pack_tag "reveal.js"
= hidden_field_tag :frete_id, @results.first.frete_id
-if current_user.usuario
	-@results.each do |result|
		.card
			.container
				.row
					.col-2
						.row
							=image_tag 'blank-avatar.webp', size: '120x120', class:"img-fluid max-width: 100% height: auto"
						%br
						.row
							%b
								Veículo
							%div
								&nbsp;&nbsp;
								= result.driver.veiculo_texto
					.col-10
						.row
							.col-1
								%b
									Nome
							.col-3
								= result.driver.nome
							.col-4
								.nota
									= result.driver.nota.html_safe
							.col-4
								%table
									%tr
										%td
											=link_to "Contato", result_path(result.id), class: "btn btn-primary float-left btn-sm"
										%td
											-if result.frete.concluido
												=link_to "Avaliar", "#", class: "btn btn-secondary float-left btn-sm disabled", "data-animation" => "fade", "data-reveal-id" => "myModal", "driver_id" => result.driver_id
											-else
												=link_to "Avaliar", "#", class: "btn btn-primary float-left btn-sm", "data-animation" => "fade", "data-reveal-id" => "myModal", "driver_id" => result.driver_id
						%br
						.row
							.col-12
								.row
									.col-4
										%b Origem-Destino
									.col-4
										%b Origem-Motorista
									.col-4
										%b Destino-Motorista
								.row
									.col-4
										= "#{result.origem_destino_km/1000} Km"
									.col-4
										= "#{result.origem_motorista_km/1000} Km"
									.col-4
										= "#{result.destino_motorista_km/1000} Km"
						%br
						.row
							.col-12
								.row
									.col-4
										%b Valor Base
									.col-4
										%b Valor por KM
									.col-4
										%b Valor Total
								.row
									.col-4
										= "R$ #{result.valor_base.real.to_s}"
									.col-4
										= "R$ #{result.valor_km.real.to_s}"
									.col-4
										= "R$ #{(result.valor_base + (result.valor_km/1000*(result.origem_motorista_km + result.destino_motorista_km + result.origem_destino_km))).real.to_s}"
	#myModal.reveal-modal.text-center
		=hidden_field_tag :selected_driver, value: ''
		%h2 Avalie seu frete!
		%p Sua opinião é importante para nós!
		%p Avaliação do motorista
		.rating-wrapper
			%input{type: "radio", name:"rating", id: "star-5"}
				%label{for:"star-5"}
			%input{type: "radio", name:"rating", id: "star-4"}
				%label{for:"star-4"}
			%input{type: "radio", name:"rating", id: "star-3"}
				%label{for:"star-3"}
			%input{type: "radio", name:"rating", id: "star-2"}
				%label{for:"star-2"}
			%input{type: "radio", name:"rating", id: "star-1"}
				%label{for:"star-1"}
		%br
		%br
		%br
		%br
		=button_tag "Avaliar", class: "avaliar-form btn btn-primary btn-sm"
		%a.close-reveal-modal ×
		:javascript
			$('.avaliar-form').on('click', function(e) {
				if($("#star-1").prop('checked') == false && $("#star-2").prop('checked') == false && $("#star-3").prop('checked') == false && $("#star-4").prop('checked') == false && $("#star-5").prop('checked') == false){
					return;
				}

				$.ajax({
					type: 'POST',
					url: '/fretes/concluir/',
					data: JSON.stringify ({
						frete_id: $("#frete_id").val(),
						star_1: $("#star-1").prop('checked'),
						star_2: $("#star-2").prop('checked'),
						star_3: $("#star-3").prop('checked'),
						star_4: $("#star-4").prop('checked'),
						star_5: $("#star-5").prop('checked'),
						driver_id: $("#selected_driver").val(),
					}),
					contentType: "application/json",
					dataType: 'json'
				}).done(function() {
					location.reload();
				});
			});
-elsif current_user.motorista
	-@results.each do |result|
		.card
			.container
				.row
					.col-2
						=image_tag 'blank-avatar.webp', size: '130x130', class:"img-fluid max-width: 100% height: auto"
					.col-10
						.row
							.col-1
								%b
									Nome
							.col-3
								= result.helper.nome
							.col-4
								.nota
									= result.helper.nota.html_safe
							.col-4
								%table
									%tr
										%td
											=link_to "Contato", result_path(result.id), class: "btn btn-primary float-left btn-sm"
										%td
											=link_to "Avaliar", "#", class: "btn btn-primary float-left btn-sm", "data-animation" => "fade", "data-reveal-id" => "myModal", "helper_id" => result.helper_id
						%br
						.row
							.col-12
								.row
									.col-4
										%b Origem-Ajudante
									.col-4
										%b Ajudante-Motorista
									.col-4
										%b Valor Base
								.row
									.col-4
										= "#{result.origem_ajudante_km/1000} Km"
									.col-4
										= "#{result.ajudante_motorista_km/1000} Km"
									.col-4
										= "R$ #{result.valor_base.real.to_s}"
	#myModal.reveal-modal.text-center
		=hidden_field_tag :selected_helper, value: ''
		%h2 Avalie seu frete!
		%p Sua opinião é importante para nós!
		%p Avaliação do ajudante
		.rating-wrapper
			%input{type: "radio", name:"rating", id: "star-5"}
				%label{for:"star-5"}
			%input{type: "radio", name:"rating", id: "star-4"}
				%label{for:"star-4"}
			%input{type: "radio", name:"rating", id: "star-3"}
				%label{for:"star-3"}
			%input{type: "radio", name:"rating", id: "star-2"}
				%label{for:"star-2"}
			%input{type: "radio", name:"rating", id: "star-1"}
				%label{for:"star-1"}
		%br
		%br
		%br
		%br
		=button_tag "Avaliar", class: "avaliar-form btn btn-primary btn-sm"
		%a.close-reveal-modal ×
		:javascript
			$('.avaliar-form').on('click', function(e) {
				if($("#star-1").prop('checked') == false && $("#star-2").prop('checked') == false && $("#star-3").prop('checked') == false && $("#star-4").prop('checked') == false && $("#star-5").prop('checked') == false){
					return;
				}
				
				$.ajax({
					type: 'POST',
					url: '/fretes/avaliar_ajudante/',
					data: JSON.stringify ({
						frete_id: $("#frete_id").val(),
						star_1: $("#star-1").prop('checked'),
						star_2: $("#star-2").prop('checked'),
						star_3: $("#star-3").prop('checked'),
						star_4: $("#star-4").prop('checked'),
						star_5: $("#star-5").prop('checked'),
						helper_id: $("#selected_helper").val(),
					}),
					contentType: "application/json",
					dataType: 'json'
				}).done(function() {
					location.reload();
				});
			});

app/views/dashboard/show.haml
-if @fretes.blank?
	.alert.alert-success
		Ainda não foi criado nenhum frete! Realize um novo frete e acompanhe aqui pelo painel!
-else
	-if current_user.usuario
		- @fretes.each do |frete|
			.card
				.container
					.row
						.col-7
							=image_tag frete.build_link, class:"img-fluid max-width: 100% height: auto"
						.col-5
							%table.auto
								%th
									Endereço Origem
								%tr
									%td
										= "#{frete.rua_origem}, #{frete.numero_origem} - #{frete.bairro_origem}, #{frete.cidade_origem} - #{frete.uf_origem}, #{frete.cep_origem}"
							%br
							%table.auto
								%th
									Endereço Destino
								%tr
									%td
										= "#{frete.rua_destino}, #{frete.numero_destino} - #{frete.bairro_destino}, #{frete.cidade_destino} - #{frete.uf_destino}, #{frete.cep_destino}"
							%div{style: "padding-top: 10px;"}
								= "Distância entre origem e destino:  #{frete.origem_destino_km.to_i/1000} km"
							%div{style: "padding-bottom: 10px;padding-top: 10px;"}
								= "Quantidade de motoristas encontrados:  #{frete.results.where.not(driver_id: nil).count}"
							-if frete.fechado
								.alert.alert-danger.text-center
									Frete Fechado
							-elsif frete.concluido
								.alert.alert-success.text-center
									Frete Concluído
							-else
								.alert.alert-info.text-center
									Frete Aberto
							%table{width: "100%"}
								%tr
									%td{width: "33%"}
										-if frete.results.where.not(driver_id: nil).count > 0
											=link_to "Lista de Motoristas", dashboard_results_path(frete.id), class: "btn btn-primary btn-block btn-lg"
										-else
											=link_to "Lista de Motoristas", dashboard_results_path(frete.id), class: "btn btn-secondary btn-block disabled btn-lg"
									%td{width: "33%"}
										-if frete.fechado || frete.concluido
											=link_to "Alterar Frete", edit_fretes_path(id:frete.id), class: "btn btn-secondary btn-block disabled btn-lg"
										-else
											=link_to "Alterar Frete", edit_fretes_path(id:frete.id), class: "btn btn-primary btn-block btn-lg"
									%td{width: "33%"}
										-if frete.fechado || frete.concluido
											=link_to "Fechar Frete", fechar_fretes_path(id:frete.id), method: :post, class: "btn btn-secondary btn-block disabled btn-lg"
										-else
											=link_to "Fechar Frete", fechar_fretes_path(id:frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
	-elsif current_user.motorista
		- @fretes.each do |frete|
			.card
				.container
					.row
						.col-7
							=image_tag frete.build_link_motorista(current_user.motorista_id), class:"img-fluid max-width: 100% height: auto"
						.col-5
							%table.auto
								%th
									Endereço Origem
								%tr
									%td
										= "#{frete.rua_origem}, #{frete.numero_origem} - #{frete.bairro_origem}, #{frete.cidade_origem} - #{frete.uf_origem}, #{frete.cep_origem}"
							%br
							%table.auto
								%th
									Endereço Destino
								%tr
									%td
										= "#{frete.rua_destino}, #{frete.numero_destino} - #{frete.bairro_destino}, #{frete.cidade_destino} - #{frete.uf_destino}, #{frete.cep_destino}"
							%div{style: "padding-top: 10px;"}
								= "Distância entre origem e destino:  #{frete.origem_destino_km/1000} km"
							%br
							-if frete.fechado
								.alert.alert-danger.text-center
									Frete Fechado
							-elsif frete.concluido
								.alert.alert-success.text-center
									Frete Concluído
							-else
								.alert.alert-info.text-center
									Frete Aberto
							%table{width: "100%"}
								%tr
									%td{width: "33%"}
										-if frete.fechado || frete.concluido
											-if frete.results.where(solicitado_motorista_id: current_user.motorista_id).count > 0
												=link_to "Atualizar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-secondary btn-block btn-lg disabled"
											-else
												=link_to "Buscar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-secondary btn-block btn-lg disabled"
										-else
											-if frete.results.where(solicitado_motorista_id: current_user.motorista_id).count > 0
												=link_to "Atualizar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
											-else
												=link_to "Buscar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"

									%td{width: "33%"}
										-if frete.results.where(solicitado_motorista_id: current_user.motorista_id).count > 0
											=link_to "Lista de Ajudantes", dashboard_results_path(frete.id), class: "btn btn-primary btn-block btn-lg"
										-else
											=link_to "Lista de Ajudantes", dashboard_results_path(frete.id), class: "btn btn-secondary btn-block btn-lg disabled"
									%td{width: "33%"}
										=link_to "Ocultar Frete", not_show_fretes_path(id:frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
	-elsif current_user.ajudante
		= javascript_pack_tag "reveal.js"
		- @fretes.each do |frete|
			.card
				.container
					.row
						.col-7
							=image_tag frete.build_link_ajudante(current_user.ajudante_id), class:"img-fluid max-width: 100% height: auto"
						.col-5
							%table.auto
								%th
									Endereço Origem
								%tr
									%td
										= "#{frete.rua_origem}, #{frete.numero_origem} - #{frete.bairro_origem}, #{frete.cidade_origem} - #{frete.uf_origem}, #{frete.cep_origem}"
							%br
							%table.auto
								%th
									Endereço Destino
								%tr
									%td
										= "#{frete.rua_destino}, #{frete.numero_destino} - #{frete.bairro_destino}, #{frete.cidade_destino} - #{frete.uf_destino}, #{frete.cep_destino}"
							%div{style: "padding-top: 10px;"}
								= "Distância entre origem e destino:  #{frete.origem_destino_km/1000} km"
							%br
							-if frete.fechado
								.alert.alert-danger.text-center
									Frete Fechado
							-elsif frete.concluido
								.alert.alert-success.text-center
									Frete Concluído
							-else
								.alert.alert-info.text-center
									Frete Aberto
							%table{width: "100%"}
								%tr
									/ %td{width: "33%"}
									/ 	-if frete.results.where(solicitado_motorista_id: current_user.motorista_id).count > 0
									/ 		=link_to "Atualizar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
									/ 	-else
									/ 		=link_to "Buscar Ajudantes", solicitar_ajudante_fretes_path(id: frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
									%td{width: "33%"}
										-if frete.concluido && Rating.where(frete_id: frete.id, nota_pelo_ajudante: true).first.blank?
											/ =link_to "Concluir", "#", class: "btn btn-secondary float-left btn-sm disabled", "data-animation" => "fade", "data-reveal-id" => "myModal", "driver_id" => result.driver_id
											=link_to "Avaliar Motorista", "#", class: "btn btn-primary btn-block btn-lg", "data-animation" => "fade", "data-reveal-id" => "myModal", "frete_id" => frete.id
										-else
											=link_to "Avaliar Motorista", dashboard_results_path(frete.id), class: "btn btn-secondary btn-block btn-lg disabled"
									%td{width: "33%"}
										=link_to "Ocultar Frete", not_show_ajudante_fretes_path(id:frete.id), method: :post, class: "btn btn-primary btn-block btn-lg"
		#myModal.reveal-modal.text-center
			=hidden_field_tag :selected_frete, value: ''
			%h2 Avalie seu frete!
			%p Sua opinião é importante para nós!
			%p Avaliação do motorista
			.rating-wrapper
				%input{type: "radio", name:"rating", id: "star-5"}
					%label{for:"star-5"}
				%input{type: "radio", name:"rating", id: "star-4"}
					%label{for:"star-4"}
				%input{type: "radio", name:"rating", id: "star-3"}
					%label{for:"star-3"}
				%input{type: "radio", name:"rating", id: "star-2"}
					%label{for:"star-2"}
				%input{type: "radio", name:"rating", id: "star-1"}
					%label{for:"star-1"}
			%br
			%br
			%br
			%br
			=button_tag "Avaliar", class: "avaliar-form btn btn-primary btn-sm"
			%a.close-reveal-modal ×
			:javascript
				$('.avaliar-form').on('click', function(e) {
					if($("#star-1").prop('checked') == false && $("#star-2").prop('checked') == false && $("#star-3").prop('checked') == false && $("#star-4").prop('checked') == false && $("#star-5").prop('checked') == false){
						return;
					}
						$.ajax({
							type: 'POST',
							url: '/fretes/ajudante_avaliar_motorista/',
							data: JSON.stringify ({
								frete_id: $("#selected_frete").val(),
								star_1: $("#star-1").prop('checked'),
								star_2: $("#star-2").prop('checked'),
								star_3: $("#star-3").prop('checked'),
								star_4: $("#star-4").prop('checked'),
								star_5: $("#star-5").prop('checked'),
							}),
							contentType: "application/json",
							dataType: 'json'
						}).done(function() {
						location.reload();
					});
				});

app/views/dashboard/view.haml
-@results.each do |result|
	%div.card
		%div.container
			%table.auto
				%th
					Nome
				%th
					Origem-Destino
				%th
					Origem-Motorista
				%th
					Destino-Motorista
				%th
					Valor Base
				%th
					Valor por Km
				%th
					Valor Total
				%tr
					%td
						= result.driver.nome
					%td
						= "#{result.origem_destino_km/1000} Km"
					%td
						= "#{result.origem_motorista_km/1000} Km"
					%td
						= "#{result.destino_motorista_km/1000} Km"
					%td
						= "R$ #{result.valor_base}"
					%td
						= "R$ #{result.valor_km}"
					%td
						= "R$ #{result.valor_base + (result.valor_km/1000*(result.origem_motorista_km + result.destino_motorista_km + result.origem_destino_km))}"
			%br
			=link_to "Detalhes", result_path(result.id), class: "btn btn-primary float-right"