config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :fretes do
  	post :fechar
  	post :concluir
  	post :not_show
    post :not_show_ajudante
  	post :solicitar_ajudante
  	post :avaliar_ajudante
  	post :ajudante_avaliar_motorista
  end
  resource :drivers
  resource :people
  resource :helpers
	get '/dashboard', to: 'dashboard#show', as: 'dashboard'
	get '/dashboard/:id/results', to: 'dashboard#results', as: 'dashboard/results'
	# get '/dashboard/:id/helper_results', to: 'dashboard#helper_results', as: 'dashboard/helper_results'
	get '/result/:id', to: 'result#result', as: 'result'
	# get '/fretes/:id/status', to: 'fretes#status'

	root to: 'dashboard#show', as: 'home'

	get '/help', to: 'help#show', as: 'help'

	# unauthenticated do
 #   root :to => 'home#show', as: 'home'
	# end

	# authenticated do
	#   root :to => 'dashboard#show', as: 'dashome'
	# end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
	has_many :results
	has_many :ratings

	def nota
		average = self.ratings.average(:nota)
		html = ''
		5.times do |nota|
			if average.to_f == 0.0
				html += '<i class="far fa-star"></i>'
			else
				if nota < average.to_i
					html += '<i class="fas fa-star"></i>'
				elsif nota == average.to_i  && (average.to_f - average.to_i).round == 1
					html += '<i class="fas fa-star-half"></i>'
				else
					html += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
				end
			end
		end
		html += "&nbsp;&nbsp;<span>#{'%.1f' % average.to_f}</span>"
		html
	end

	def veiculo_texto
		case self.tipo_veiculo
		when 1
			"Pickup"
		when 2
			"Van/Vuc"
		when 3
			"Caminhão"
		end
	end

end

app/models/frete.rb
class Frete < ApplicationRecord
	has_many :results, autosave: true
	has_many :ratings, autosave: true
	accepts_nested_attributes_for :results

	validates :cep_origem, presence: true

	def build_link
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where.not(driver_id: nil).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_motorista(driver_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"
		self.results.where(driver_id: driver_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		self.results.where(solicitado_motorista_id: driver_id).each do |result|
			link += "&markers=color:blue|label:A|#{result.latitude_ajudante},#{result.longitude_ajudante}"
			# link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end

	def build_link_ajudante(helper_id)
		link = "https://maps.googleapis.com/maps/api/staticmap?size=600x300&maptype=roadmap&markers=color:red|label:O|#{self.latitude_origem},#{self.longitude_origem}&markers=color:red|label:D|#{self.latitude_destino},#{self.longitude_destino}"

		result_ajudante = self.results.where(helper_id: helper_id).first
		link += "&markers=color:blue|label:A|#{result_ajudante.latitude_ajudante},#{result_ajudante.longitude_ajudante}"

		self.results.where(driver_id: result_ajudante.solicitado_motorista_id).each do |result|
			link += "&markers=color:green|label:M|#{result.latitude_motorista},#{result.longitude_motorista}"
			link += "&path=color:0x007a00|weight:5|enc:#{result.origem_polyline}"
		end
		
		link += "&path=color:0x0000ff|weight:5|enc:#{self.polyline}"
		link += "&key=AIzaSyB-MUPe6AKnZLJ-cO5OgLACRY7ngbi0hR4"
	end
end

app/models/helper.rb
class Helper < ApplicationRecord
	has_many :ratings
	has_many :results

	def nota
		average = self.ratings.average(:nota)
		html = ''
		5.times do |nota|
			if average.to_f == 0.0
				html += '<i class="far fa-star"></i>'
			else
				if nota < average.to_i
					html += '<i class="fas fa-star"></i>'
				elsif nota == average.to_i  && (average.to_f - average.to_i).round == 1
					html += '<i class="fas fa-star-half"></i>'
				else
					html += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
				end
			end
		end
		html += "&nbsp;&nbsp;<span>#{'%.1f' % average.to_f}</span>"
		html
	end
end

app/models/helper_rating.rb
class HelperRating < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :driver
	belongs_to :frete
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :frete
	belongs_to :driver
	belongs_to :helper
end

app/models/state.rb
class State < ApplicationRecord

	def self.estados
		self.pluck(:sigla)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :is_complete, :user_name

  def user_name
  	if self.is_complete
  		if self.usuario
  			Person.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		elsif self.motorista
  			Driver.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		else
  			Helper.find_by(user_id: self.id).try(:nome).try(:split).try(:first).try(:camelize)
  		end
  	else
  		'Cadastre-se!'
  	end
  end

  def is_complete
  	self.usuario || self.ajudante || self.motorista
  end

  def usuario_id
  	Person.find_by(user_id: self.id).id
  end

  def motorista_id
    Driver.find_by(user_id: self.id).id
  end

  def ajudante_id
    Helper.find_by(user_id: self.id).id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fretes_helper.rb
module FretesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mudfacil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha256-Kg2zTcFO9LXOc7IwcBx1YeUBJmekycsnTsq2RuFHSZU=" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/bfef90e897.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%=favicon_link_tag asset_path('mudfacil.png'), type: 'image/png'%>
  </head>

  <body>
    <%= render "shared/sidebar"%>
    <div id="content">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_sidebar.haml
#sidebar
  %header
    -if user_signed_in?
      %a{:href => '/'}=image_tag "mudfacil_texto.png", :style => 'padding: 10px;'
    -else
      %a{:href => '/users/sign_in'}=image_tag "mudfacil_texto.png", :style => 'padding: 10px;'
  %ul.nav
    -if user_signed_in?
      %li
        %a{:href => '#homeSubmenu', "data-toggle"=>"collapse", class:"fas fa-user-circle"}
          %span Olá, #{current_user.user_name}
        %ul.collapse.list-unstyled#homeSubmenu
          %li
            %a{:href => '/users/sign_out', class:"fas fa-door-closed"}
              %span Sair
          %li
            %a{:href => '/users/edit', class:"fas fa-user-edit"}
              %span Alterar Senha
      - if current_user.is_complete
        -if current_user.usuario
          %li
            %a{:href => '/fretes/new', class:"fas fa-route"}
              %span Novo Frete
        %li
          %a{:href => '/dashboard', class:"fas fa-th-list"}
            %span Painel
        -if current_user.usuario
          %li
            = link_to "<span>Editar Usuário</span>".html_safe, edit_people_path(id: current_user.usuario_id),class: "fas fa-user"
        -elsif current_user.motorista
          %li
            = link_to "<span>Editar Motorista</span>".html_safe, edit_drivers_path(id: current_user.motorista_id),class: "fas fa-truck"
        -elsif current_user.ajudante
          %li
            = link_to "<span>Editar Ajudante</span>".html_safe, edit_helpers_path(id: current_user.ajudante_id),class: "fas fa-people-carry"
      -else
        %li
          %a{:href => '/people/new', class:"fas fa-user"}
            %span Cadastrar Usuário
        %li
          %a{:href => '/drivers/new', class:"fas fa-truck"}
            %span Cadastrar Motorista
        %li
          %a{:href => '/helpers/new', class:"fas fa-people-carry"}
            %span Cadastrar Ajudante
      %li
        %a{:href => '/help', class:"fas fa-question-circle"}
          %span Ajuda
    -else
      %li
        %a{:href => '/users/sign_in', class:"fas fa-door-open"}
          %span Entrar
      %li
        %a{:href => '/users/sign_up', class:"fas fa-user-edit"}
          %span Cadastre-se
      / %li
      /   %a{:href => '/users/password/new', class:"far fa-user"}
      /     %span Esqueceu?

:javascript
  $(document).on("click", "li", function() {
    window.location = $(this).find("a").attr("href");
  });