config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :fretes do
  	post :fechar
  	post :concluir
  	post :not_show
    post :not_show_ajudante
  	post :solicitar_ajudante
  	post :avaliar_ajudante
  	post :ajudante_avaliar_motorista
  end
  resource :drivers
  resource :people
  resource :helpers
	get '/dashboard', to: 'dashboard#show', as: 'dashboard'
	get '/dashboard/:id/results', to: 'dashboard#results', as: 'dashboard/results'
	# get '/dashboard/:id/helper_results', to: 'dashboard#helper_results', as: 'dashboard/helper_results'
	get '/result/:id', to: 'result#result', as: 'result'
	# get '/fretes/:id/status', to: 'fretes#status'

	root to: 'dashboard#show', as: 'home'

	get '/help', to: 'help#show', as: 'help'

	# unauthenticated do
 #   root :to => 'home#show', as: 'home'
	# end

	# authenticated do
	#   root :to => 'dashboard#show', as: 'dashome'
	# end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
 def new
		@helper = Helper.new()
		@estados = State.estados
	end

	def edit
		@helper = Helper.find(params.permit![:id])
		@estados = State.estados
	end

	def update
		@helper = Helper.find(params.permit![:helper][:id])
		@helper.update_attributes(params.permit![:helper])
		redirect_to edit_helpers_path(id: @helper.id), notice: "Cadastro atualizado com sucesso!"
	end

	def create
		@helper = Helper.new(params.permit![:helper])
		@helper.user_id = current_user.id
		@helper.save
		current_user.update(ajudante: true)
		redirect_to edit_helpers_path(id: @helper.id), notice: "Cadastro concluído com sucesso!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/fretes_helper.rb
module FretesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/helpers/_form.haml
= javascript_pack_tag "busca_cep.js"
= javascript_pack_tag "set_mask.js"
= bootstrap_form_with(model: @helper, url: helpers_path, class: "needs-validation", html: { novalidate: true }) do |f|
	=f.hidden_field :id
	.card
		-if @helper.new_record?
			%h5 Cadastrar Ajudante
		-else
			%h5 Editar Ajudante
		.row
			.col-5
				=f.text_field :nome, required: true
			.col-4
				=f.text_field :cpf, class: "c_cpf", required: true
			.col-3
				=f.text_field :data_nascimento, value: (l(f.object.data_nascimento) rescue nil), class: "c_data"
			.col-4
				=f.text_field :email, required: true
			.col-3
				=f.text_field :telefone, class: "c_telefone"
			.col-3
				=f.text_field :celular, class: "c_celular"
		.row
			.col-3
				=f.text_field :area_km, required: true
			.col-2
				=f.text_field :valor, class: "c_dinheiro", required: true
		.row
			.col-2
				=f.text_field :cep, class: "c_cep", id: "cep", required: true
			.col-8
				=f.text_field :rua, id: "rua", required: true
			.col-2
				=f.text_field :numero, required: true
			.col-4
				=f.text_field :complemento
			.col-3
				=f.text_field :bairro, id: "bairro"
			.col-3
				=f.text_field :cidade, id: "cidade", required: true
			.col-2
				=f.select :uf, options_for_select(@estados, f.object.uf),{}, id: "uf", required: true
		.row
			.col
				-if @helper.new_record?
					= f.submit "Gravar", id: "btn", class: "btn btn-primary float-right"
				-else
					= f.submit "Salvar Alterações", id: "btn", class: "btn btn-primary float-right"
:javascript
	(function() {
	'use strict';
		window.addEventListener('load', function() {
			// Fetch all the forms we want to apply custom Bootstrap validation styles to
			var forms = document.getElementsByClassName('needs-validation');
			// Loop over them and prevent submission
			var validation = Array.prototype.filter.call(forms, function(form) {
			form.addEventListener('submit', function(event) {
				if (form.checkValidity() === false) {
					event.preventDefault();
					event.stopPropagation();
				}
					form.classList.add('was-validated');
				}, false);
			});
		}, false);
	})();

app/views/helpers/edit.haml
=render 'form'

app/views/helpers/new.haml
=render 'form'